### ISSUE TITLE
HeroCard formflow  returning an Exception.

### ISSUE THREAD

**Issue by muneebrana23** [somak12/BotDemo#1]
@somak12 
HeroCard Formflow returning an Exception. 
Exception: Object reference not set to an instance of an object.
[File of type 'text/plain']

Attachment:
![screenshot 82](https://user-images.githubusercontent.com/32091742/32682903-5fd0d092-c699-11e7-93cd-fbc1add0a2e6.png)

**Comment by somak12** [comment]
Thanks for the bug report. And sorry for the mistake in the first place. Have fixed the issue you can check now.

**Comment by muneebrana23** [comment]
Somak Sir i'm working on Bot . And some need help so can i ask you if i
stuck at some point?

**Comment by somak12** [comment]
@muneebrana23 sure i will be happy to help if i can. You can checkout my blogs on bot https://medium.com/@somakdas
Comment there if required and i will try to answer your questions.

**Comment by muneebrana23** [comment]
@somak12  in your article on chatbotlife.com  formflow part 1 we were able to edit the customer information . . but in part 2 customer can't edit its info. . can you guide about edit option in part 2.
